# Generated by Django 2.2.5 on 2019-09-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'child', 'verbose_name_plural': 'children'},
        ),
    ]
