# Generated by Django 2.2.5 on 2019-09-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190913_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'chi', 'verbose_name_plural': 'children'},
        ),
    ]
