# Generated by Django 2.2.5 on 2019-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190913_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='we ight'),
        ),
    ]
