# Generated by Django 2.2.5 on 2019-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('H', 'Hot'), ('D', 'Discount'), ('', '')], max_length=2),
        ),
    ]
