# Generated by Django 2.2.5 on 2019-09-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190922_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Clock', 'Clock'), ('Cabinet', 'Cabinet')], max_length=20),
        ),
    ]
